api = "0.7"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/node-module-bom"
  id = "paketo-buildpacks/node-module-bom"
  name = "Paketo Node Module Bill of Materials Generator Buildpack"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/node-module-bom/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:owasp:cyclonedx-node-module:3.0.7:*:*:*:*:*:*:*"
    id = "cyclonedx-node-module"
    licenses = ["Apache-2.0", "ECL-2.0", "SHL-0.51", "SHL-0.5"]
    name = "CycloneDX Node.js Module"
    purl = "pkg:npm/%40cyclonedx/bom@3.0.7"
    sha256 = "7974bf0e776c587c5e1ad44a7e75477ab5863ee037fd84f153727295ffd6d2cf"
    source = "https://registry.npmjs.org/@cyclonedx/bom/-/bom-3.0.7.tgz"
    source_sha256 = "da1b87cec24a2b029871254068c4cc575de15b6dcc3135e4c7019af898a5aa4c"
    stacks = ["io.buildpacks.stacks.bionic", "io.buildpacks.stacks.jammy"]
    uri = "https://deps.paketo.io/cyclonedx-node-module/cyclonedx-node-module_3.0.7_linux_x64_bionic_7974bf0e.tgz"
    version = "3.0.7"

  [[metadata.dependency-constraints]]
    constraint = "*"
    id = "cyclonedx-node-module"
    patches = 1

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.buildpacks.stacks.jammy"
