api = "0.7"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/node-module-bom"
  id = "paketo-buildpacks/node-module-bom"
  name = "Paketo Node Module Bill of Materials Generator Buildpack"
  sbom-formats = ["application/vnd.cyclonedx+json","application/spdx+json","application/vnd.syft+json"]

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
